// <auto-generated />
using System;
using EasyERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyERP.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyERP.Models.Order", b =>
                {
                    b.Property<int>("IntOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntOrderId"));

                    b.Property<DateTime>("DtOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("NumQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductIntProductId")
                        .HasColumnType("int");

                    b.Property<string>("StrCustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntOrderId");

                    b.HasIndex("ProductIntProductId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("EasyERP.Models.Product", b =>
                {
                    b.Property<int>("IntProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntProductId"));

                    b.Property<decimal>("NumStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NumUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StrProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntProductId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("EasyERP.Models.Order", b =>
                {
                    b.HasOne("EasyERP.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductIntProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
